select
    order_id,
    source,
    channel,
    customer_id,
    order_ts,
    order_date,
    status as order_status,
    status_ts,
    is_cancelled,
    is_returned,
    paid_at,
    shipped_at,
    delivered_at,
    cancelled_at,
    returned_at,
    payment_method,
    shipping_city,
    shipping_postal_code,
    lines_count,
    units,
    gross_amount,
    discount_amount,
    net_amount,
    shipping_fee,
    total_amount,
    source_total_amount
from {{ source('lake', 'orders') }}
